# Generated by Django 3.1.3 on 2021-05-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomechlabwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='attachment',
            field=models.FileField(upload_to='media - copy/'),
        ),
    ]
